// <auto-generated />
using CIM.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CIM.Migrations
{
    [DbContext(typeof(CIMContext))]
    [Migration("20230330223054_TwoMoreDevices")]
    partial class TwoMoreDevices
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("CIM.Models.Device", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(9)
                        .HasColumnType("TEXT");

                    b.Property<string>("OU")
                        .HasColumnType("TEXT");

                    b.Property<string>("PI")
                        .HasColumnType("TEXT");

                    b.Property<string>("PU")
                        .HasColumnType("TEXT");

                    b.Property<string>("ServiceTag")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Devices");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "CHASTEST",
                            OU = "\\chas.local\\CLINIC\\DEPT\\",
                            PI = "monitor issues",
                            PU = "Biggles T. McClure",
                            ServiceTag = "1234abc",
                            Status = "Deployable"
                        },
                        new
                        {
                            Id = 2,
                            Name = "CHASTEST2",
                            OU = "\\chas.local\\CLINIC2\\DEPT2\\",
                            PI = "wifi issues",
                            PU = "Bo 'Bobo' BoBoBo",
                            ServiceTag = "5678def",
                            Status = "Needs Imaged"
                        },
                        new
                        {
                            Id = 3,
                            Name = "CHASTEST3",
                            OU = "\\chas.local\\CLINIC3\\DEPT3\\",
                            PI = "self esteem issues",
                            PU = "Hugh Mungus",
                            ServiceTag = "910ghij",
                            Status = "Deployed"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
